webtalk_init -webtalk_dir C:/Users/manis/Desktop/Verilog/FSM/moore101_overlapping/moore101_overlapping.sim/sim_1/behav/xsim/xsim.dir/moore101_overlapping_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 13 16:07:15 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "88988d67-2eef-4303-a73d-86fe8bc1523e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "712527c8c22f4709b6289e3969dadbc4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3935625706 -regid "" -xml C:/Users/manis/Desktop/Verilog/FSM/moore101_overlapping/moore101_overlapping.sim/sim_1/behav/xsim/xsim.dir/moore101_overlapping_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/manis/Desktop/Verilog/FSM/moore101_overlapping/moore101_overlapping.sim/sim_1/behav/xsim/xsim.dir/moore101_overlapping_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/manis/Desktop/Verilog/FSM/moore101_overlapping/moore101_overlapping.sim/sim_1/behav/xsim/xsim.dir/moore101_overlapping_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
