# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/axi_des/axi_des.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des || ORIG_REF_NAME==axi_des} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_processing_system7_0_0/axi_des_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_processing_system7_0_0 || ORIG_REF_NAME==axi_des_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_axi_gpio_0_0/axi_des_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_0_0 || ORIG_REF_NAME==axi_des_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_axi_gpio_1_0/axi_des_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_1_0 || ORIG_REF_NAME==axi_des_axi_gpio_1_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_ps7_0_axi_periph_0/axi_des_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_des_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_rst_ps7_0_100M_0/axi_des_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_des_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_xbar_0/axi_des_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_xbar_0 || ORIG_REF_NAME==axi_des_xbar_0} -quiet] -quiet

# IP: bd/axi_des/ip/axi_des_auto_pc_0/axi_des_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_des_auto_pc_0 || ORIG_REF_NAME==axi_des_auto_pc_0} -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_processing_system7_0_0/axi_des_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_processing_system7_0_0 || ORIG_REF_NAME==axi_des_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_axi_gpio_0_0/axi_des_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_0_0 || ORIG_REF_NAME==axi_des_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_axi_gpio_0_0/axi_des_axi_gpio_0_0_ooc.xdc

# XDC: bd/axi_des/ip/axi_des_axi_gpio_0_0/axi_des_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_0_0 || ORIG_REF_NAME==axi_des_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_axi_gpio_1_0/axi_des_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_1_0 || ORIG_REF_NAME==axi_des_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_axi_gpio_1_0/axi_des_axi_gpio_1_0_ooc.xdc

# XDC: bd/axi_des/ip/axi_des_axi_gpio_1_0/axi_des_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_axi_gpio_1_0 || ORIG_REF_NAME==axi_des_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_rst_ps7_0_100M_0/axi_des_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_des_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_rst_ps7_0_100M_0/axi_des_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_des_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_des_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_des/ip/axi_des_auto_pc_0/axi_des_auto_pc_0_ooc.xdc

# XDC: bd/axi_des/axi_des_ooc.xdc
